export const ACTIONS = ({
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',
  USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',
  
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
});