export const ACTIONS = ({
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  FACEBOOK_START_LOADING: 'FACEBOOK_START_LOADING',
  FACEBOOK_STOP_LOADING: 'FACEBOOK_STOP_LOADING',

  RESET_STATUS: 'RESET_STATUS',
  FACEBOOK_RESET_STATUS: 'FACEBOOK_RESET_STATUS',

  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_CONFLICT: 'USER_SIGNUP_CONFLICT',
  USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',
  
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_NOTFOUND: 'USER_LOGIN_NOTFOUND',
  USER_LOGIN_UNAUTHORIZED: 'USER_LOGIN_UNAUTHORIZED',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  USER_SOCIAL_AUTH_SUCCESS: 'USER_SOCIAL_AUTH_SUCCESS',
  USER_SOCIAL_AUTH_ERROR: 'USER_SOCIAL_AUTH_ERROR',

  USER_SWITCH_ROLE_SUCCESS: 'USER_SWITCH_ROLE_SUCCESS',
  USER_SWITCH_ROLE_ERROR: 'USER_SWITCH_ROLE_ERROR'
});